### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by CallMeFib3r** [crespoter/oasis#1]
Hi Crespoter,

I came up with a logo for your project. This is won't cost you anything so you can consider it as a contribution. If you like it I can send you all the files you need. If you would like me to slightly modify the logo you can certainly let me know. 

Kind regards,
Fiber 
![presentation-03](https://user-images.githubusercontent.com/37731582/38777848-168e113e-40af-11e8-93fd-9d6cd28c852f.png)

**Comment by crespoter** [comment]
@CallMeFib3r 
The logo is quite nice and I wish I could use it , but this repository is actually an assignment submission for a job interview and hence cant accept any outside help. 
However we have a Developer community started recently which is currently lacking a good logo. We would really appreciate it if you are willing to contribute to the community. .

**Comment by CallMeFib3r** [comment]
Hi @crespoter I completely understand. I would love to contribute to the community. Is their in any way a open-source project or GitHub repository tied to the community?

**Comment by crespoter** [comment]
@CallMeFib3r ,
Thanks for helping out.  The aim of this community is to spread the knowledge of AI through meetups and training sessions. Please start an issue in the following github repository.  
https://github.com/AIDeveloperCommunity/aidevelopercommunity.github.io

**Comment by CallMeFib3r** [comment]
Awesome @crespoter! I will start working on a logo. Stay tuned!

**Comment by crespoter** [comment]
@CallMeFib3r ,
I dont mean to rush , but how's the logo coming along?

**Comment by CallMeFib3r** [comment]
Hi @crespoter,
I haven't had a lot of time this week. I did brainstorm a little but I am yet to come up with a nice concept. If you gave something in mind feel free to let me know. It might help the entire process.

**Comment by crespoter** [comment]
@CallMeFib3r , Good to know you are still with us.  I cant think of anything off the top of my head. I will let you know if I do. Again , thanks for helping us out 😄

**Comment by crespoter** [comment]
@CallMeFib3r  Here is the link for our pitch. Maybe you could get some takeaway ideas.
https://prezi.com/view/hIW14W8lJ1zCT0D6ppyg/

**Comment by CallMeFib3r** [comment]
@crespoter an issue has been submitted :smile: https://github.com/AIDeveloperCommunity/aidevelopercommunity.github.io/issues/12

**Comment by crespoter** [comment]
@CallMeFib3r  , I saw the contribution. We really appreciate your help. If you dont mind , can we stay connected. Can you ping me at davidchristie.k15@iiits.in so that we can continue this conversation in private.
